[package]
name = "desse-derive"
version = "0.2.1"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Ultra fast binary serialization and deserialization for types with size known at compile time."
homepage = "https://github.com/devashishdxt/desse"
repository = "https://github.com/devashishdxt/desse"
categories = ["encoding"]
keywords = ["serialization", "encoding", "binary", "macro", "no_std"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "devashishdxt/desse" }

[dependencies]
syn = "2.0"
quote = "0.6"
proc-macro2 = "0.4"

[lib]
name = "desse_derive"
path = "src/lib.rs"
doctest = false
proc-macro = true
